spring:
  application:
    name: registry-data-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/openid_auth
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
#   data: classpath:psql_database_tables.sql,classpath:security-schema.sql,classpath:users.sql,classpath:clients.sql,classpath:scopes.sql
  resources: 
    add-mappings: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: update
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080





